// services/devicesConfig.js
export const devicesConfig = [
  {
    name: 'VR1',
    deviceID: 3,
    port: 'COM3',
    baudRate: 57600,
    timeout: 12000,
    retryInterval: 15000,
    maxRetries: 3,
    unstable: false,
    readDataFunction: 'readDataVr1',
    serviceModule: './services/pechVr1ModbusService.js',
  },
  {
    name: 'VR2',
    deviceID: 4,
    port: 'COM3',
    baudRate: 57600,
    timeout: 12000,
    retryInterval: 15000,
    maxRetries: 3,
    unstable: false,
    readDataFunction: 'readDataVr2',
    serviceModule: './services/pechVr2ModbusService.js',
  },
  {
    name: 'VR1_TimeCounter',
    deviceID: 5,
    port: 'COM3',
    baudRate: 57600,
    timeout: 12000,
    retryInterval: 15000,
    maxRetries: 3,
    unstable: false,
    readDataFunction: 'readVr1TimeCounter',
    serviceModule: './services/vr1TimeCounterService.js',
  },
  {
    name: 'VR2_TimeCounter',
    deviceID: 6,
    port: 'COM3',
    baudRate: 57600,
    timeout: 12000,
    retryInterval: 15000,
    maxRetries: 3,
    unstable: false,
    readDataFunction: 'readVr2TimeCounter',
    serviceModule: './services/vr2TimeCounterService.js',
  },
  {
    name: 'MPA2',
    deviceID: 6,
    port: 'COM16',
    baudRate: 9600,
    timeout: 3000,
    retryInterval: 15000,
    maxRetries: 3,
    unstable: false,
    readDataFunction: 'readDataMpa2',
    serviceModule: './services/pechMpa2ModbusService.js',
  },
  {
    name: 'MPA3',
    deviceID: 5,
    port: 'COM16',
    baudRate: 9600,
    timeout: 3000,
    retryInterval: 15000,
    maxRetries: 3,
    unstable: false,
    readDataFunction: 'readDataMpa3',
    serviceModule: './services/pechMpa3ModbusService.js',
  },
  {
    name: 'Sushilka1',
    deviceID: 1,
    port: 'COM4',
    baudRate: 57600,
    timeout: 12000,
    retryInterval: 15000,
    maxRetries: 3,
    unstable: false,
    readDataFunction: 'readDataSushilka1',
    serviceModule: './services/sushilka1ModbusService.js',
  },
  {
    name: 'Sushilka2',
    deviceID: 2,
    port: 'COM5',
    baudRate: 57600,
    timeout: 30000,
    retryInterval: 15000,
    maxRetries: 3,
    unstable: false,
    readDataFunction: 'readDataSushilka2',
    serviceModule: './services/sushilka2ModbusService.js',
  },
  {
    name: 'Mill1',
    deviceID: 0x02,
    port: 'COM8',
    baudRate: 57600,
    timeout: 12000,
    retryInterval: 15000,
    maxRetries: 3,
    unstable: false,
    readDataFunction: 'readDataMill1',
    serviceModule: './services/mill1ModbusService.js',
  },
  {
    name: 'Mill2',
    deviceID: 0x03,
    port: 'COM11',
    baudRate: 57600,
    timeout: 12000,
    retryInterval: 15000,
    maxRetries: 3,
    unstable: true,
    readDataFunction: 'readDataMill2',
    serviceModule: './services/mill2ModbusService.js',
  },
  {
    name: 'ReactorK296',
    deviceID: 0x01,
    port: 'COM11',
    baudRate: 57600,
    timeout: 12000,
    retryInterval: 15000,
    maxRetries: 3,
    unstable: true,
    readDataFunction: 'readDataReactorK296',
    serviceModule: './services/reactor296ModbusService.js',
  },
  {
    name: 'Mill10b',
    deviceID: 0x01,
    port: 'COM1',
    baudRate: 9600,
    timeout: 12000,
    retryInterval: 15000,
    maxRetries: 3,
    unstable: false,
    readDataFunction: 'readDataMill10b',
    serviceModule: './services/mill10bModbusService.js',
  },
  {
    name: 'DD972',
    deviceID: 0x48,
    port: 'COM17',
    baudRate: 9600,
    timeout: 12000,
    retryInterval: 15000,
    maxRetries: 3,
    unstable: false,
    readDataFunction: 'readDataDD972',
    serviceModule: './services/uzliUchetaService.js',
  },
    {
    name: 'DD973',
    deviceID: 0x49,
    port: 'COM17',
    baudRate: 9600,
    timeout: 12000,
    retryInterval: 15000,
    maxRetries: 3,
    unstable: false,
    readDataFunction: 'readDataDD973',
    serviceModule: './services/uzliUchetaService.js',
  },
    {
    name: 'DE093',
    deviceID: 0x5D,
    port: 'COM17',
    baudRate: 9600,
    timeout: 12000,
    retryInterval: 15000,
    maxRetries: 3,
    unstable: false,
    readDataFunction: 'readDataDE093',
    serviceModule: './services/uzliUchetaService.js',
  },
    {
    name: 'DD576',
    deviceID: 0x4C,
    port: 'COM17',
    baudRate: 9600,
    timeout: 12000,
    retryInterval: 15000,
    maxRetries: 3,
    unstable: false,
    readDataFunction: 'readDataDD576',
    serviceModule: './services/uzliUchetaService.js',
  },
    {
    name: 'DD569',
    deviceID: 0x45,
    port: 'COM17',
    baudRate: 9600,
    timeout: 12000,
    retryInterval: 15000,
    maxRetries: 3,
    unstable: false,
    readDataFunction: 'readDataDD569',
    serviceModule: './services/uzliUchetaService.js',
  },
    {
    name: 'DD923',
    deviceID: 0x17,
    port: 'COM17',
    baudRate: 9600,
    timeout: 12000,
    retryInterval: 15000,
    maxRetries: 3,
    unstable: false,
    readDataFunction: 'readDataDD923',
    serviceModule: './services/uzliUchetaService.js',
  },
  {
    name: 'DD924',
    deviceID: 0x18,
    port: 'COM17',
    baudRate: 9600,
    timeout: 12000,
    retryInterval: 15000,
    maxRetries: 3,
    unstable: false,
    readDataFunction: 'readDataDD924',
    serviceModule: './services/uzliUchetaService.js',
  },
  {
    name: 'press3',
    deviceID: 0x03,
    port: 'COM14',
    baudRate: 19200,
    timeout: 12000,
    retryInterval: 15000,
    maxRetries: 3,
    unstable: false,
    readDataFunction: 'readDataPress3',
    serviceModule: './services/press3ModbusService.js',
  },
];

export const serialDevicesConfig = [
  {
    name: 'НОТИС1',
    address: 1,
    port: 'COM12',
    baudRate: 115200,
    serviceModule: './services/notisService.js',
    readDataFunction: 'readDataNotis1'
  },
  {
    name: 'НОТИС2',
    address: 2,
    port: 'COM12',
    baudRate: 115200,
    serviceModule: './services/notisService.js',
    readDataFunction: 'readDataNotis2'
  }
];