// services/devicesConfig.js
export const devicesConfig = [
  {
    name: 'VR1',
    deviceID: 3,
    port: 'COM8',
    baudRate: 57600,
    timeout: 12000,
    retryInterval: 15000,
    maxRetries: 3,
    readDataFunction: 'readDataVr1',
    serviceModule: './services/pechVr1ModbusService.js',
  },
  {
    name: 'VR2',
    deviceID: 4,
    port: 'COM8',
    baudRate: 57600,
    timeout: 12000,
    retryInterval: 15000,
    maxRetries: 3,
    readDataFunction: 'readDataVr2',
    serviceModule: './services/pechVr2ModbusService.js',
  },
  {
    name: 'Sushilka1',
    deviceID: 1,
    port: 'COM10',
    baudRate: 57600,
    timeout: 12000,
    retryInterval: 15000,
    maxRetries: 3,
    readDataFunction: 'readDataSushilka1',
    serviceModule: './services/sushilka1ModbusService.js',
  },
  {
    name: 'Sushilka2',
    deviceID: 2,
    port: 'COM3',
    baudRate: 57600,
    timeout: 30000,
    retryInterval: 15000,
    maxRetries: 3,
    readDataFunction: 'readDataSushilka2',
    serviceModule: './services/sushilka2ModbusService.js',
  },
  // {
  //   name: 'Mill1',
  //   deviceID: 0x02,
  //   port: 'COM13',
  //   baudRate: 57600,
  //   timeout: 12000,
  //   retryInterval: 15000,
  //   maxRetries: 3,
  //   readDataFunction: 'readDataMill1',
  //   serviceModule: './services/mill1ModbusService.js',
  // },
  // {
  //   name: 'Mill2',
  //   deviceID: 0x03,
  //   port: 'COM7',
  //   baudRate: 57600,
  //   timeout: 12000,
  //   retryInterval: 15000,
  //   maxRetries: 3,
  //   readDataFunction: 'readDataMill2',
  //   serviceModule: './services/mill2ModbusService.js',
  // },
  // {
  //   name: 'ReactorK296',
  //   deviceID: 0x01,
  //   port: 'COM7',
  //   baudRate: 57600,
  //   timeout: 12000,
  //   retryInterval: 15000,
  //   maxRetries: 3,
  //   readDataFunction: 'readDataReactorK296',
  //   serviceModule: './services/reactor296ModbusService.js',
  // },
];
